### ISSUE TITLE
An error occurred in e4mc

### ISSUE THREAD

**Issue by lucananni93** [vgskye/e4mc-minecraft-architectury#75]
Once I Open LAN, I do not receive any e4mc address for my friends to connect and **An error occurred in e4mc** message appears.

Follows my log file:

```
[11:55:16] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.9
[11:55:17] [main/INFO]: Loading 57 mods:
	- e4mc_minecraft 5.2.1
	   \-- folk_sisby_kaleido-config 0.3.1+1.3.1
	- fabric-api 0.102.0+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.68+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.16+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.19+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.5.0+c5e2b5c6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.27+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.16+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae06d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.4+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df360d1
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.2+60c3209bd1
	   |-- fabric-object-builder-api-v1 15.2.0+a551f7a4d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.12+65089712d1
	   |-- fabric-registry-sync-v0 5.1.2+60c3209bd1
	   |-- fabric-renderer-api-v1 3.4.0+c705a49cd1
	   |-- fabric-renderer-indigo 1.7.0+c705a49cd1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b1d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.86+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.16+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.1.0+176f9036d1
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21
	- sodium 0.6.5+mc1.21.1
	   \-- fabric-resource-loader-v0 1.3.1+5b5275af19
	- tlskincape 1.34
[11:55:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/Users/lnanni/Library/Application%20Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[11:55:17] [main/INFO]: Compatibility level set to JAVA_17
[11:55:17] [main/INFO]: Compatibility level set to JAVA_21
[11:55:17] [main/INFO]: Loaded configuration file for Sodium: 43 options available, 0 override(s) found
[11:55:18] [main/INFO]: Searching for graphics cards...
[11:55:18] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[11:55:19] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 376 milliseconds
[11:55:25] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:55:25] [Render thread/INFO]: Setting user: lucananni93
[11:55:25] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[11:55:26] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[11:55:26] [Render thread/INFO]: OpenGL Vendor: Intel Inc.
[11:55:26] [Render thread/INFO]: OpenGL Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
[11:55:26] [Render thread/INFO]: OpenGL Version: 4.1 INTEL-22.5.11
[11:55:27] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, e4mc_minecraft, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, sodium
[11:55:27] [Worker-Main-6/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[11:55:28] [Worker-Main-4/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[11:55:29] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:55:29] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:55:29] [Render thread/INFO]: OpenAL initialized on device External Headphones
[11:55:29] [Render thread/INFO]: Sound engine started
[11:55:30] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11:55:30] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[11:55:30] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:55:30] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:55:30] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[11:55:30] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:55:30] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[11:55:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:55:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:55:30] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[11:55:30] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:55:30] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:55:30] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[11:55:30] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[11:55:30] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[12:06:08] [Render thread/INFO]: Loaded 1290 recipes
[12:06:08] [Render thread/INFO]: Loaded 1399 advancements
[12:06:09] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.719 ms
[12:06:10] [Server thread/INFO]: Starting integrated minecraft server version 1.21
[12:06:10] [Server thread/INFO]: Generating keypair
[12:06:20] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:06:21] [Render thread/INFO]: Preparing spawn area: 0%
[12:06:21] [Render thread/INFO]: Preparing spawn area: 0%
[12:06:21] [Render thread/INFO]: Time elapsed: 736 ms
[12:06:21] [Server thread/INFO]: Changing view distance to 12, from 10
[12:06:21] [Server thread/INFO]: Changing simulation distance to 12, from 0
[12:06:22] [Server thread/INFO]: lucananni93[local:E:9b7e4f1c] logged in with entity id 113 at (-17.660296223503583, 63.0, -17.469778184356343)
[12:06:22] [Server thread/INFO]: lucananni93 joined the game
[12:06:22] [Render thread/INFO]: Started 2 worker threads
[12:06:22] [Render thread/INFO]: Loaded 257 advancements
[12:06:23] [Render thread/INFO]: calculated cape performance:TEXTURE_272, middle time: 2.5
[12:06:23] [Server thread/INFO]: Saving and pausing game...
[12:06:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:overworld
[12:06:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:the_nether
[12:06:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:the_end
[12:06:24] [Render thread/INFO]: can use texture size:TEXTURE_272, middle time: 1.7
[12:06:26] [Server thread/INFO]: Saving and pausing game...
[12:06:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:overworld
[12:06:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:the_nether
[12:06:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:the_end
[12:06:28] [Render thread/INFO]: Using default channel type
[12:06:28] [Render thread/INFO]: Using default channel type
[12:06:28] [Render thread/INFO]: Started serving on 49877
[12:06:28] [Render thread/INFO]: [System] [CHAT] Local game hosted on port [49877]
[12:06:28] [e4mc_minecraft-init/INFO]: req: https://broker.e4mc.link/getBestRelay GET
[12:06:28] [e4mc_minecraft-init/INFO]: [System] [CHAT] An error occurred in e4mc
[12:06:28] [e4mc_minecraft-init/ERROR]: Uncaught exception in thread "e4mc_minecraft-init"
java.lang.RuntimeException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at knot/link.e4mc.QuiclimeSession.start(QuiclimeSession.java:396) ~[e4mc_minecraft-fabric-5.2.1.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:960) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133) ~[java.net.http:?]
	at knot/link.e4mc.QuiclimeSession.getRelay(QuiclimeSession.java:247) ~[e4mc_minecraft-fabric-5.2.1.jar:?]
	at knot/link.e4mc.QuiclimeSession.start(QuiclimeSession.java:264) ~[e4mc_minecraft-fabric-5.2.1.jar:?]
	... 1 more
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:145) ~[?:?]
	at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64) ~[?:?]
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:612) ~[?:?]
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[?:?]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.unwrapBuffer(SSLFlowDelegate.java:542) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:438) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:269) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207) ~[java.net.http:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
[12:06:30] [Server thread/INFO]: lucananni93 lost connection: Disconnected
[12:06:30] [Server thread/INFO]: lucananni93 left the game
[12:06:30] [Server thread/INFO]: Stopping singleplayer server as player logged out
[12:06:30] [Server thread/INFO]: Stopping server
[12:06:30] [Server thread/INFO]: Saving players
[12:06:30] [Server thread/INFO]: Saving worlds
[12:06:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:overworld
[12:06:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:the_nether
[12:06:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Server_OLD]'/minecraft:the_end
[12:06:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (Server): All chunks are saved
[12:06:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:06:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:06:31] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:06:31] [Render thread/INFO]: Stopping worker threads
[12:10:35] [Render thread/INFO]: Stopping!
```

**Comment by vgskye** [comment]
please confirm that https://broker.e4mc.link/getBestRelay is reachable from browser. if not, it's an ISP problem I cannot fix.

**Comment by lucananni93** [comment]
Yes it is reachable!

**Comment by vgskye** [comment]
that is strange. please confirm above URL is reachable via secure connection and your internet connection does not have any root CA based HTTPS monitoring?

**Comment by Gleb635478** [comment]
I have the same problem, I don't understand how to solve it, my friend is fine, but when I try to log in or create a LAN, I get an error, can you tell me how to solve this problem?I didn't really understand what you meant above.

**Comment by Timemaster108** [comment]
Potential duplicate of #92

**Comment by vgskye** [comment]
@lucananni93 what ISP are you using?
