### ISSUE TITLE
e4mc doesnt work on my setup.

### ISSUE THREAD

**Issue by F-alling** [vgskye/e4mc-minecraft-architectury#9]
Im running ubuntu 22.04 and am using crafty controller to control my server. It tries to access the home directory instead of the correct directory (i think) It tries to access `/home/crafty/.e4mc-cache/FILE` instead of `/var/opt/minecraft/crafty/crafty-4/servers/1dd3ba3e-0770-43b0-a7d1-378b9a544bad/FILE`
` [e4mc_minecraft-init/ERROR]: Uncaught exception in thread "e4mc_minecraft-init"
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at link.e4mc.QuiclimeSession.start(QuiclimeSession.java:384) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.incubator.codec.quic.Quic.ensureAvailability(Quic.java:81) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:78) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:378) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at link.e4mc.QuiclimeSession.start(QuiclimeSession.java:257) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	... 1 more
Caused by: java.lang.ExceptionInInitializerError
	at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:46) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:78) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:378) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at link.e4mc.QuiclimeSession.start(QuiclimeSession.java:257) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	... 1 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /home/crafty/.e4mc_cache/libnetty_quiche_linux_x86_64_63.so (No such file or directory)
	at io.netty.incubator.codec.quic.Quiche.loadNativeLibrary(Quiche.java:108) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:69) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:46) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:78) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:378) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at link.e4mc.QuiclimeSession.start(QuiclimeSession.java:257) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	... 1 more
Caused by: java.io.FileNotFoundException: /home/crafty/.e4mc_cache/libnetty_quiche_linux_x86_64_63.so (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289) ~[?:?]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230) ~[?:?]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:118) ~[?:?]
	at io.netty.incubator.codec.quic.Quiche.loadNativeLibrary(Quiche.java:101) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:69) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:46) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:78) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:378) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	at link.e4mc.QuiclimeSession.start(QuiclimeSession.java:257) ~[e4mc_minecraft-5.0.0-fabric.jar:?]
	... 1 more`

**Comment by vgskye** [comment]
please don't use e4mc for persistent dedicated servers, it's maintained as best-effort and is generally not recommended

**Comment by F-alling** [comment]
What should I use instead?

I dont have many options other then reverse proxies and there are not many that are headless.

**Comment by F-alling** [comment]
also "persistent dedicated servers" if its intended to just be used for like a temporary server, then why is it under the "server" enviroment?

**Comment by vgskye** [comment]
> also "persistent dedicated servers" if its intended to just be used for like a temporary server, then why is it under the "server" enviroment?

modrinth guidelines, e4mc is meant for logical server and doesn't do anything on logical client
